### ISSUE TITLE
Interactive date markings in agenda not working in v1.8.0+ (TypeError: marking.reduce is not a function)

### ISSUE THREAD

**Issue by tankers746** [wix/react-native-calendars#220]
## Description

Version 1.8.0 seems to have broken "interactive" date marking in agenda view. Version 1.7.1 is working fine.

## Expected Behavior

Setting prop:
` markingType={'interactive'}`

Marks dates as shown in the example code.

## Observed Behavior

Opening the agenda results in the following exception:

```
TypeError: marking.reduce is not a function

getDrawingStyle (react-native-calendars\src\calendar\day\interactive\index.js:60)
Day (react-native-calendars\src\calendar\day\interactive\index.js:32)
constructClassInstance (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:1400)
updateClassComponent (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:1477)
beginWork (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:1585)
performUnitOfWork (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:2279)
workLoop (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:2303)
performWork (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:2343)
batchedUpdates (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:2514)
performFiberBatchedUpdates (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:201)
stackBatchedUpdates (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:195)
batchedUpdates (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:205)
batchedUpdatesWithControlledComponents (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:214)
_receiveRootNodeIDEvent (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:3315)
receiveTouches (react-native\Libraries\Renderer\ReactNativeFiber-prod.js:3329)
__callFunction (react-native\Libraries\BatchedBridge\MessageQueue.js:306)
(anonymous) (react-native\Libraries\BatchedBridge\MessageQueue.js:108)
__guard (react-native\Libraries\BatchedBridge\MessageQueue.js:269)
MessageQueue.callFunctionReturnFlushedQueue (react-native\Libraries\BatchedBridge\MessageQueue.js:107)
(anonymous) (debuggerWorker.js:72)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.8.0
* `npm ls react-native`: react-native@0.49.5

Also specify:

1. Phone/emulator/simulator & version: iPhone 6S - iOS 11.0.3

## Reproducible Demo

The following is taken from the example, I've un-commented the marking props:
https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js

```
<Agenda
        items={this.state.items}
        loadItemsForMonth={this.loadItems.bind(this)}
        selected={'2017-05-16'}
        renderItem={this.renderItem.bind(this)}
        renderEmptyDate={this.renderEmptyDate.bind(this)}
        rowHasChanged={this.rowHasChanged.bind(this)}
        markingType={'interactive'}
        markedDates={{
          '2017-05-08': [{textColor: '#666'}],
          '2017-05-09': [{textColor: '#666'}],
          '2017-05-14': [{startingDay: true, color: 'blue'}, {endingDay: true, color: 'blue'}],
          '2017-05-21': [{startingDay: true, color: 'blue'}],
          '2017-05-22': [{endingDay: true, color: 'gray'}],
          '2017-05-24': [{startingDay: true, color: 'gray'}],
          '2017-05-25': [{color: 'gray'}],
          '2017-05-26': [{endingDay: true, color: 'gray'}]}}
         monthFormat={'yyyy'}
        // theme={{calendarBackground: 'red', agendaKnobColor: 'green'}}
        //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
/>

```

**Comment by tankers746** [comment]
Someone with the same error back in July. The solution is not applicable here however.

https://github.com/wix/react-native-calendars/issues/113

**Comment by tautvilas** [comment]
Fixed in 1.9.1
